/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ihoneymon' at '14. 3. 14 오전 10:26' with Gradle 1.11
 *
 * @author ihoneymon, @date 14. 3. 14 오전 10:26
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
