/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'ihoneymon' at '14. 3. 14 오전 10:26' with Gradle 1.11
 *
 * @author ihoneymon, @date 14. 3. 14 오전 10:26
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
